'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const request = require('supertest');
const { createApplication, sessions, safePosition, validCoordPair } = require('../server/server');

const vehicle = { nickname: 'Carro teste', plate: 'ABC1D23', brand: 'Marca', model: 'Modelo', year: 2024, version: '1.0', engine: '1.0', transmission: 'Manual', fuel: 'Gasolina', city: 10, road: 14, tank: 45, price: 6.19 };
function setup(t) { sessions.clear(); const context = createApplication({ databasePath: ':memory:', sessionSecret: 'test-secret-with-at-least-32-characters', silent: true }); t.after(() => { sessions.clear(); context.database.close(); }); return context; }
function register(agent, overrides = {}) { return agent.post('/api/auth/register').send({ name: 'Usuário Teste', email: 'teste@example.com', password: 'Senha123', ...overrides }); }

test('health check confirma API e banco', async (t) => { const { app } = setup(t); const response = await request(app).get('/api/health').expect(200); assert.equal(response.body.database, 'connected'); });
test('cadastro cria usuário, hash e sessão autenticada', async (t) => { const { app, database } = setup(t); const agent = request.agent(app); await register(agent).expect(201); const row = database.prepare('SELECT email, password_hash FROM users').get(); assert.equal(row.email, 'teste@example.com'); assert.notEqual(row.password_hash, 'Senha123'); assert.match(row.password_hash, /^\$2[aby]\$/); await agent.get('/api/auth/me').expect(200); });
test('cadastro rejeita entrada inválida e e-mail duplicado', async (t) => { const { app } = setup(t); const agent = request.agent(app); await register(agent, { password: 'fraca' }).expect(400); await register(agent).expect(201); await request(app).post('/api/auth/register').send({ name: 'Outro', email: 'TESTE@example.com', password: 'Outra123' }).expect(409); });
test('login rejeita senha incorreta e aceita credenciais corretas', async (t) => { const { app } = setup(t); await register(request.agent(app)).expect(201); await request(app).post('/api/auth/login').send({ email: 'teste@example.com', password: 'Errada123' }).expect(401); const agent = request.agent(app); await agent.post('/api/auth/login').send({ email: 'teste@example.com', password: 'Senha123' }).expect(200); await agent.get('/api/auth/me').expect(200); });
test('logout revoga sessão', async (t) => { const { app } = setup(t); const agent = request.agent(app); await register(agent).expect(201); await agent.post('/api/auth/logout').expect(204); await agent.get('/api/auth/me').expect(401); });
test('painel e API protegida negam usuário não autenticado', async (t) => { const { app } = setup(t); await request(app).get('/').expect(302).expect('Location', '/login.html'); await request(app).get('/api/vehicles/reference').expect(401); await request(app).post('/api/sessions').send({ vehicle }).expect(401); });
test('sessão de rastreamento é persistida e isolada por proprietário', async (t) => { const { app, database } = setup(t); const owner = request.agent(app); const stranger = request.agent(app); await register(owner).expect(201); await register(stranger, { email: 'outro@example.com' }).expect(201); const created = await owner.post('/api/sessions').send({ vehicle }).expect(201); assert.match(created.body.qrCode, /^data:image\/png;base64,/); assert.equal(database.prepare('SELECT COUNT(*) AS total FROM tracking_sessions').get().total, 1); await owner.get(`/api/sessions/${created.body.id}`).expect(200); await stranger.get(`/api/sessions/${created.body.id}`).expect(404); });
test('valida coordenadas, posições e perfil de veículo', () => { assert.equal(safePosition({ latitude: 91, longitude: 0 }), null); assert.equal(safePosition({ latitude: '-23.5', longitude: '-46.6', accuracy: 12 }).accuracy, 12); assert.deepEqual(validCoordPair('-42.5,-19.4'), [-42.5, -19.4]); assert.equal(validCoordPair('x,20'), null); });
